[profile.default]
src = "src"
out = "out"
load_from_env_file = true
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    
    # Standard path for forge-std
    'forge-std/=lib/forge-std/src/'
]

# Tests to be done inside of src/ directory
tests = 'src/tests'

[rpc_endpoints]
avalanche_fuji = "https://avalanche-fuji-c-chain-rpc.publicnode.com"
arbitrum_sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"
unichain_sepolia = "https://unichain-sepolia-rpc.publicnode.com"
